### PR TITLE
ES-743

### PR DESCRIPTION
**Pull request by bunsy-0900**
### Issue
[Mobile(IOS): Retry button is not working in Forgot Password screen and text alignment is not proper in pop up message](https://mosip.atlassian.net/browse/ES-743)

### Solution
- reload document using `document`
- use `text-balance`

### CODE REVIEW

**Review by panharith-0118 — APPROVED** [review]

**Review by aranaravi — COMMENTED** [review]
When we use reload it will be like the user loading the page for first time and will take longer time. Better use alternate approach.

**Comment by bunsy-0900** [comment]
Previous, we use navigate(0). However, it is not working on iOS 17, thus we fallback to use reload().

**Comment by bunsy-0900** [comment]
https://github.com/remix-run/react-router/issues/8600

**Review by aranaravi — APPROVED** [review]

**Comment by dreadwood** [comment]
The problem is still relevant

**Pull request merged**
